# Generated by Django 3.2.4 on 2021-06-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('div_p', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DJ30',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('avg_momentum', models.FloatField()),
                ('ep', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Etf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('momentum_12_1', models.FloatField()),
                ('ma10', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('user', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SP500',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('avg_momentum', models.FloatField()),
                ('ep', models.FloatField()),
            ],
        ),
    ]
