# Generated by Django 3.2.4 on 2021-07-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momentum_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj30',
            name='momentum_12_2',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sp500',
            name='momentum_12_2',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
