# Generated by Django 3.2.4 on 2021-07-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momentum_app', '0002_auto_20210703_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj30',
            name='low_range',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sp500',
            name='low_range',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
